@id = 0196877b-6d1f-776d-9a64-9998c2f39ce3
@url = http://localhost:5196/api/v1/articles

###
GET {{url}}

###
PUT {{url}}

###
POST {{url}}

###
GET {{url}}/tags

###
GET {{url}}/{{id}}

###
DELETE {{url}}/{{id}}
