networks:
  mongo_backend_network:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mongo_backend_network
    volumes:
      - ./.container/mongodb:/data/db
    
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongo
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "password"
    ports:
      - "8081:8081"
    networks:
      - mongo_backend_network
    volumes:
      - ./.container/mongo_express:/data/db
